### ISSUE TITLE
`nan` results of `clr`

### ISSUE THREAD

**Issue by PauBadiaM** [ntessore/composition_stats#2]
Hi @ntessore 

First of all thanks for implementing this in python, such a library was really missing in the ecosystem.

I was comparing some results of `clr` transformation between `compositon_stats` and the R package [`compostions`](https://cran.r-project.org/web/packages/compositions/compositions.pdf) and observed that `compositon_stats.clr` cannot handle null or empty features, here's an example:

```python
import numpy as np
from composition_stats import closure, clr

arr = np.array([740, 0, 29, 403, 51, 4916, 143, 1, 1])
clr(closure(arr))
```
```
array([inf, nan, inf, inf, inf, inf, inf, inf, inf])
```

On the other hand, here's the result of `compositions` with the same example data:
```R
library(compositions)

arr <- c(740, 0, 29, 403, 51, 4916, 143, 1, 1)
clr(acomp(arr))
```
```
[1]  2.4356748  0.0000000 -0.8036796  1.8279611 -0.2391498  4.3292751  0.7918692
[8] -4.1709754 -4.1709754
```

In my particular case, I would want to compute the `clr` even when there are 0s since I have other samples that have values for all features. Is there a way to reproduce the behavior of the R package?

Thank you for your time!

**Comment by PauBadiaM** [comment]
After looking at the source code, it looks like they just ignore the 0 values. As a solution, one way to reproduce the R result would be to adapt your `clr` function to:

```python
def clr(mat):
    msk = mat != 0.
    lmat = np.log(mat, where=msk)
    gm = lmat.mean(axis=-1, keepdims=True, where=msk)
    return np.where(msk, (lmat - gm).squeeze(), lmat)
```

**Comment by ntessore** [comment]
Hi @PauBadiaM, thanks for reporting this discrepancy between the codes.

I am not sure I like setting zero entries to zero unconditionally. IIRC, the limit of `clr([..., x, ...])` as `x` approaches zero would send its entry to `-inf` and everything else to `+inf`. So it seems inappropriate to have a discontinuous limit `x=0` where the entry is simply ignored.

Perhaps we could add a keyword argument `ignore_zero=False` that can be used to switch behaviours?

**Comment by PauBadiaM** [comment]
That would be great. I would also add a small note in the `clr` docs pointing that to reproduce `compositions` behavior set `ignore_zero` to `True`. Thanks! :)

**Comment by ntessore** [comment]
Since you have basically done it already, would you like to open a PR with the changes?
